version: '3'

services:
  web:
    container_name: web
    build: .
    command: python -m sanic tfidf.app --host=0.0.0.0 --port=8000 --workers=1 --debug
    environment:
        TFIDF_PORT: 8000
        TFIDF_DB_HOST: db
        TFIDF_DB_USER: postgres
        TFIDF_DB_PASSWORD: example
        TFIDF_DB_PORT: 5432
        TFIDF_DB_NAME: wiki
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: wiki
